/**
 * Generated by Reactium
 * DO NOT directly edit this file !!!!!!
 */

module.exports = {
    domains: {
        ExitingPage: {
            name: 'ExitingPage',
            implied: 'ExitingPage',
            original:
                'src/app/components/ExitingPage/reactium-domain-exitingpage.js',
        },
        FeatureTester: {
            name: 'FeatureTester',
            implied: 'FeatureTester',
            original:
                'src/app/components/FeatureTester/reactium-domain-featuretester.js',
        },
        Greeter: {
            name: 'Greeter',
            implied: 'Greeter',
            original: 'src/app/components/Greeter/reactium-domain-greeter.js',
        },
        LoadingSpinner: {
            name: 'LoadingSpinner',
            implied: 'Loading',
            original:
                'reactium_modules/@atomic-reactor/reactium-core/components/Loading/reactium-domain-Loading.js',
        },
    },
    relative: {
        'src/app/components/ExitingPage': 'ExitingPage',
        'src/app/components/FeatureTester': 'FeatureTester',
        'src/app/components/Greeter': 'Greeter',
        'reactium_modules/@atomic-reactor/reactium-core/components/Loading':
            'LoadingSpinner',
    },
};
