/**
 * Generated by Reactium
 * DO NOT directly edit this file !!!!!!
 */
import op from 'object-path';
import _ from 'underscore';
import { isBrowserWindow } from '@atomic-reactor/reactium-sdk-core';

const deps = {};
const reqs = {
    allRoutes: {
        AdvancedLoader: {
            req: () => {
                return import(
                    '../src/app/components/AdvancedLoader/reactium-route-advancedloader'
                );
            },
            file:
                '../src/app/components/AdvancedLoader/reactium-route-advancedloader',
        },
        DataLoader: {
            req: () => {
                return import(
                    '../src/app/components/DataLoader/reactium-route-dataloader'
                );
            },
            file: '../src/app/components/DataLoader/reactium-route-dataloader',
        },
        ExitingPage: {
            req: () => {
                return import(
                    '../src/app/components/ExitingPage/reactium-route-exitingpage'
                );
            },
            file:
                '../src/app/components/ExitingPage/reactium-route-exitingpage',
        },
        FeatureTester: {
            req: () => {
                return import(
                    '../src/app/components/FeatureTester/reactium-route-featuretester'
                );
            },
            file:
                '../src/app/components/FeatureTester/reactium-route-featuretester',
        },
        Greeter: {
            req: () => {
                return import(
                    '../src/app/components/Greeter/reactium-route-greeter'
                );
            },
            file: '../src/app/components/Greeter/reactium-route-greeter',
        },
        Hello: {
            req: () => {
                return import(
                    '../src/app/components/Hello/reactium-route-hello'
                );
            },
            file: '../src/app/components/Hello/reactium-route-hello',
        },
        HelloWorld: {
            req: () => {
                return import(
                    '../src/app/components/HelloWorld/reactium-route-helloworld'
                );
            },
            file: '../src/app/components/HelloWorld/reactium-route-helloworld',
        },
        HookTester: {
            req: () => {
                return import(
                    '../src/app/components/HookTester/reactium-route-hooktester'
                );
            },
            file: '../src/app/components/HookTester/reactium-route-hooktester',
        },
    },
    allServices: {},
    allHooks: {
        AdvancedLoader: {
            req: () => {
                return import(
                    '../src/app/components/AdvancedLoader/reactium-hooks-advancedloader'
                );
            },
            file:
                '../src/app/components/AdvancedLoader/reactium-hooks-advancedloader',
        },
        DataLoader: {
            req: () => {
                return import(
                    '../src/app/components/DataLoader/reactium-hooks-dataloader'
                );
            },
            file: '../src/app/components/DataLoader/reactium-hooks-dataloader',
        },
        ExitingPage: {
            req: () => {
                return import(
                    '../src/app/components/ExitingPage/reactium-hooks-exitingpage'
                );
            },
            file:
                '../src/app/components/ExitingPage/reactium-hooks-exitingpage',
        },
        FeatureTester: {
            req: () => {
                return import(
                    '../src/app/components/FeatureTester/reactium-hooks-featuretester'
                );
            },
            file:
                '../src/app/components/FeatureTester/reactium-hooks-featuretester',
        },
        HookTester: {
            req: () => {
                return import(
                    '../src/app/components/HookTester/reactium-hooks-hooktester'
                );
            },
            file: '../src/app/components/HookTester/reactium-hooks-hooktester',
        },
        TransitionPage: {
            req: () => {
                return import(
                    '../src/app/components/TransitionPage/reactium-hooks-transitionpage'
                );
            },
            file:
                '../src/app/components/TransitionPage/reactium-hooks-transitionpage',
        },
        UserDetail: {
            req: () => {
                return import(
                    '../src/app/components/UserDetail/reactium-hooks-userdetail'
                );
            },
            file: '../src/app/components/UserDetail/reactium-hooks-userdetail',
        },
        'reactium-api': {
            req: () => {
                return import('@atomic-reactor/reactium-api/reactium-hooks');
            },
            file: '@atomic-reactor/reactium-api/reactium-hooks',
        },
        'reactium-capability': {
            req: () => {
                return import(
                    '@atomic-reactor/reactium-capability/reactium-hooks'
                );
            },
            file: '@atomic-reactor/reactium-capability/reactium-hooks',
        },
        app: {
            req: () => {
                return import(
                    '@atomic-reactor/reactium-core/app/reactium-hooks-App'
                );
            },
            file: '@atomic-reactor/reactium-core/app/reactium-hooks-App',
        },
        LoadingSpinner: {
            req: () => {
                return import(
                    '@atomic-reactor/reactium-core/components/Loading/reactium-hooks-Loading'
                );
            },
            file:
                '@atomic-reactor/reactium-core/components/Loading/reactium-hooks-Loading',
        },
        sdk: {
            req: () => {
                return import(
                    '@atomic-reactor/reactium-core/sdk/reactium-hooks-core-sdk'
                );
            },
            file: '@atomic-reactor/reactium-core/sdk/reactium-hooks-core-sdk',
        },
        'reactium-role': {
            req: () => {
                return import('@atomic-reactor/reactium-role/reactium-hooks');
            },
            file: '@atomic-reactor/reactium-role/reactium-hooks',
        },
        'reactium-setting': {
            req: () => {
                return import(
                    '@atomic-reactor/reactium-setting/reactium-hooks'
                );
            },
            file: '@atomic-reactor/reactium-setting/reactium-hooks',
        },
        'reactium-user': {
            req: () => {
                return import('@atomic-reactor/reactium-user/reactium-hooks');
            },
            file: '@atomic-reactor/reactium-user/reactium-hooks',
        },
    },
};

const manifest = {
    get: () => {
        const domainLoaders = {};
        for (const [name, domains] of Object.entries(reqs)) {
            const loaders = [];
            for (const [domain, item] of Object.entries(domains)) {
                loaders.push({
                    name,
                    domain,
                    loader: () =>
                        new Promise((resolve, reject) => {
                            try {
                                item.req().then(module => {
                                    resolve({
                                        name,
                                        domain,
                                        module,
                                    });
                                });
                            } catch (error) {
                                const where = isBrowserWindow()
                                    ? ' in browser '
                                    : ' on server ';
                                console.error(
                                    `Error loading manifest resource "${item.file}" of type ${name} from domain ${domain}${where}`,
                                    error,
                                );
                                resolve(false);
                            }
                        }),
                });
            }

            op.set(domainLoaders, [name], loaders);
        }

        return domainLoaders;
    },
    list: () => {
        return {
            allRoutes: {
                type: 'route',
                imports: [
                    '../src/app/components/AdvancedLoader/reactium-route-advancedloader',
                    '../src/app/components/DataLoader/reactium-route-dataloader',
                    '../src/app/components/ExitingPage/reactium-route-exitingpage',
                    '../src/app/components/FeatureTester/reactium-route-featuretester',
                    '../src/app/components/Greeter/reactium-route-greeter',
                    '../src/app/components/Hello/reactium-route-hello',
                    '../src/app/components/HelloWorld/reactium-route-helloworld',
                    '../src/app/components/HookTester/reactium-route-hooktester',
                ],
                originals: {
                    '../src/app/components/AdvancedLoader/reactium-route-advancedloader':
                        'src/app/components/AdvancedLoader/reactium-route-advancedloader.js',
                    '../src/app/components/DataLoader/reactium-route-dataloader':
                        'src/app/components/DataLoader/reactium-route-dataloader.js',
                    '../src/app/components/ExitingPage/reactium-route-exitingpage':
                        'src/app/components/ExitingPage/reactium-route-exitingpage.js',
                    '../src/app/components/FeatureTester/reactium-route-featuretester':
                        'src/app/components/FeatureTester/reactium-route-featuretester.js',
                    '../src/app/components/Greeter/reactium-route-greeter':
                        'src/app/components/Greeter/reactium-route-greeter.js',
                    '../src/app/components/Hello/reactium-route-hello':
                        'src/app/components/Hello/reactium-route-hello.js',
                    '../src/app/components/HelloWorld/reactium-route-helloworld':
                        'src/app/components/HelloWorld/reactium-route-helloworld.js',
                    '../src/app/components/HookTester/reactium-route-hooktester':
                        'src/app/components/HookTester/reactium-route-hooktester.js',
                },
            },
            allServices: {
                type: 'services',
                imports: [],
                originals: {},
            },
            allHooks: {
                type: 'hooks',
                imports: [
                    '../src/app/components/AdvancedLoader/reactium-hooks-advancedloader',
                    '../src/app/components/DataLoader/reactium-hooks-dataloader',
                    '../src/app/components/ExitingPage/reactium-hooks-exitingpage',
                    '../src/app/components/FeatureTester/reactium-hooks-featuretester',
                    '../src/app/components/HookTester/reactium-hooks-hooktester',
                    '../src/app/components/TransitionPage/reactium-hooks-transitionpage',
                    '../src/app/components/UserDetail/reactium-hooks-userdetail',
                    '@atomic-reactor/reactium-api/reactium-hooks',
                    '@atomic-reactor/reactium-capability/reactium-hooks',
                    '@atomic-reactor/reactium-core/app/reactium-hooks-App',
                    '@atomic-reactor/reactium-core/components/Loading/reactium-hooks-Loading',
                    '@atomic-reactor/reactium-core/sdk/reactium-hooks-core-sdk',
                    '@atomic-reactor/reactium-role/reactium-hooks',
                    '@atomic-reactor/reactium-setting/reactium-hooks',
                    '@atomic-reactor/reactium-user/reactium-hooks',
                ],
                originals: {
                    '../src/app/components/AdvancedLoader/reactium-hooks-advancedloader':
                        'src/app/components/AdvancedLoader/reactium-hooks-advancedloader.js',
                    '../src/app/components/DataLoader/reactium-hooks-dataloader':
                        'src/app/components/DataLoader/reactium-hooks-dataloader.js',
                    '../src/app/components/ExitingPage/reactium-hooks-exitingpage':
                        'src/app/components/ExitingPage/reactium-hooks-exitingpage.js',
                    '../src/app/components/FeatureTester/reactium-hooks-featuretester':
                        'src/app/components/FeatureTester/reactium-hooks-featuretester.js',
                    '../src/app/components/HookTester/reactium-hooks-hooktester':
                        'src/app/components/HookTester/reactium-hooks-hooktester.js',
                    '../src/app/components/TransitionPage/reactium-hooks-transitionpage':
                        'src/app/components/TransitionPage/reactium-hooks-transitionpage.js',
                    '../src/app/components/UserDetail/reactium-hooks-userdetail':
                        'src/app/components/UserDetail/reactium-hooks-userdetail.js',
                    '@atomic-reactor/reactium-api/reactium-hooks':
                        'reactium_modules/@atomic-reactor/reactium-api/reactium-hooks.js',
                    '@atomic-reactor/reactium-capability/reactium-hooks':
                        'reactium_modules/@atomic-reactor/reactium-capability/reactium-hooks.js',
                    '@atomic-reactor/reactium-core/app/reactium-hooks-App':
                        'reactium_modules/@atomic-reactor/reactium-core/app/reactium-hooks-App.js',
                    '@atomic-reactor/reactium-core/components/Loading/reactium-hooks-Loading':
                        'reactium_modules/@atomic-reactor/reactium-core/components/Loading/reactium-hooks-Loading.js',
                    '@atomic-reactor/reactium-core/sdk/reactium-hooks-core-sdk':
                        'reactium_modules/@atomic-reactor/reactium-core/sdk/reactium-hooks-core-sdk.js',
                    '@atomic-reactor/reactium-role/reactium-hooks':
                        'reactium_modules/@atomic-reactor/reactium-role/reactium-hooks.js',
                    '@atomic-reactor/reactium-setting/reactium-hooks':
                        'reactium_modules/@atomic-reactor/reactium-setting/reactium-hooks.js',
                    '@atomic-reactor/reactium-user/reactium-hooks':
                        'reactium_modules/@atomic-reactor/reactium-user/reactium-hooks.js',
                },
            },
        };
    },
};

export default manifest;
